name: Deploy Docker Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './docker'
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 'Build and Push Inventory Image (llama-factory)'
        run: |
          cd llama-factory
          docker build --rm . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pytorch-2.2.0-llama-factory
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pytorch-2.2.0-llama-factory

      - name: 'Cleanup after llama-factory'
        run: |
          docker system prune --all --force
          docker builder prune --all --force

      # - name: 'Build and Push Inventory Image (torch-lm-dev)'
      #   run: |
      #     cd torch-lm-dev
      #     docker build --rm . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pytorch-2.3.1-lm-dev
      #     docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pytorch-2.3.1-lm-dev

      - name: 'Build and Push Inventory Image (torch-sft)'
        run: |
          cd sft
          docker build --rm . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pytorch-2.2.0-sft
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pytorch-2.2.0-sft

      - name: 'Final Cleanup'
        run: |
          docker system prune --all --force
          docker builder prune --all --force